export const ROUTER = {
  HOME: "/",
  CART: "cart",
  PRODUCT: "/product",
  CATEGORY: "/category",
  CATEGORIES: "/categories",
  ORDER: "/order",
  ORDER_PLACING: "/order-placing",
  MY_ORDERS: "/my-orders",
  PROFILE: "/profile",
  PROFILE_EDIT: "/profile/edit",
  PROFILE_ORDERS: "/profile/orders",
  PROFILE_ADDRESSES: "/profile/addresses",
  PROFILE_NOTIFICATIONS: "/profile/notifications",
  PROFILE_ABOUT: "/profile/about",
  PROFILE_LANGUAGE: "/profile/language",
  CHAT: "/chat",
  BOOKING: "/booking",
  ATMOSPHERE: "/atmosphere",
};
